name: test1
friction: 0.3
walls:
  - pos:   !!python/tuple [0.5, 0.41, 0.5]
    scale: !!python/tuple [3.5, 0.5, 3.5]
    sticky: True
    floor: 0.45
  - pos:   !!python/tuple [0.35, 0.5, 0.5]
    scale: !!python/tuple [0.5, 2.3, 3.5]
  - pos:   !!python/tuple [0.65, 0.5, 0.5]
    scale: !!python/tuple [0.5, 2.3, 3.5]
  - pos:   !!python/tuple [0.5, 0.5, 0.35]
    scale: !!python/tuple [3.5, 2.3, 0.5]
  - pos:   !!python/tuple [0.5, 0.5, 0.65]
    scale: !!python/tuple [3.5, 2.3, 0.5]

res: 150
seg_len: .36
pause_len: .08
motion:
  y0: .47
  dy: .05
  x0: .43
  dx: .07

fluid:
  type: snow
  density: 1000
  friction: 0.3
fluid_scale: 0.3
v0: -.1

